name: Publish to PyPI


on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    name: build distributions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: "3.11"

      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Check metadata
        run: |
          python -m pip install --upgrade twine
          python -m twine check dist/*

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: dist
          path: dist/

  publish:
    name: publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: dist
          path: dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
